apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion_emploi_du_temps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gestion_emploi_du_temps
  template:
    metadata:
      labels:
        app: gestion_emploi_du_temps
    spec:
      containers:
        - name: gestion_emploi_du_temps
          image: gestion_emploi_du_temps:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/gestion_emploi"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"