spring:
  cloud:
    gateway:
      routes:
        - id: gestion-etudiants
          uri: http://localhost:8081
          predicates:
            - Path=/api/etudiants/**
        - id: gestion-profs
          uri: http://localhost:8082
          predicates:
            - Path=/api/professeurs/**
        - id: gestion-cours
          uri: http://localhost:8083
          predicates:
            - Path=/api/cours/**
        - id: gestion-classes
          uri: http://localhost:8084
          predicates:
            - Path=/api/classes/**
        - id: gestion-emplois
          uri: http://localhost:8085
          predicates:
            - Path=/api/emplois/**

      globalcors:  # 🔄 Déplacé au bon niveau
        corsConfigurations:
          '[/**]':  # 🛠 Correction du chemin (toutes les routes)
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
            allowedHeaders: "*"
